# Generated by Django 5.1.4 on 2025-01-19 21:32

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_games', to=settings.AUTH_USER_MODEL)),
                ('user_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_active_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('animation_file', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='')),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_animations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TempFrame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animation_title', models.CharField(max_length=20)),
                ('frame_number', models.PositiveIntegerField()),
                ('file', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_frames', to='game.activegame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_img', to=settings.AUTH_USER_MODEL)),
                ('user_shaed_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_img_shared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
