# Generated by Django 5.1.4 on 2025-01-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_messagegame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempframe',
            old_name='user_shaed_with',
            new_name='user_share_with',
        ),
    ]
