# Generated by Django 5.1.4 on 2025-01-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_messagegame_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animations',
            name='animation_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
