# Generated by Django 5.1.4 on 2025-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_animations_animation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animations',
            name='animation_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
